svg_maps.svg_maps_entity.*.*:
  type: config_entity
  label: 'Svg maps entity config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    type:
      type: string
      label: 'Plugin'
    maps_path:
      type: sequence
      label: 'Maps Svg path'
      sequence:
        type: svg_maps.type.[%parent.type]
    uuid:
      type: string
