svg_maps.type.generic:
  type: mapping
  label: 'Generic type configuration'
  mapping:
    path:
      type: text
      label: 'Path'
    detailed_path:
      type: text
      label: 'Detailed path'
