webform_mass_email.settings:
  type: config_object
  label: 'Webform Mass Email settings'
  mapping:
    cron:
      type: integer
      label: 'Cron time'
    html:
      type: boolean
      label: 'Allow sending as HTML'
    log:
      type: boolean
      label: 'Log emails'
