svg_maps.type.usa_states:
  type: mapping
  label: 'Generic type configuration'
  mapping:
    path:
      type: text
      label: 'Path'
    detailed_path:
      type: text
      label: 'Detailed path'
    class:
      type: string
      label: 'Class attribute'
    code:
      type: string
      label: 'Code'
